export const codeBlockOptions = {
    readOnly: true,
    domReadOnly: true,
    contextmenu: false,
    folding: false,
    lineNumbers: "off",
    minimap: { enabled: false },
    glyphMargin: false,
    scrollbar: {
        vertical: "hidden",
        horizontal: "hidden",
        useShadows: false,
    },
    scrollBeyondLastLine: false,
    renderLineHighlight: "none",
    hover: { enabled: false },
    renderLineNumbers: "off",
    hideCursorInOverviewRuler: true,
    overviewRulerLanes: 0,
    renderIndentGuides: false,
    padding: {
        top: 16,
        right: 16,
        bottom: 16,
        left: 16,
    },
};